### ISSUE TITLE
[469e-RC8] Linux fullscreen issues with SDL3 compat and multi monitor

### ISSUE THREAD

**Issue by XenGi** [OldUnreal/UnrealTournamentPatches#1775]
Game launches fine in windowed mode but fullscreen on a 1440p screen with resolution set to 1080p results in a stretched window where I only see the lower left corner. If I set the resolution to the native screen resolution I get this error:

```
Inconsistent SDL window flags

History: USDLViewport::ResizeViewport <- UOpenGLRenderDevice::SetRes <- UOpenGLRenderDevice::Init <- USDLViewport::TryRenderDevice <- USDLViewport::OpenWindow <- UGameEngine::Init <- InitEngine <- main

Exiting due to error
```

**Comment by salvalie** [comment]
@stijn-volckaert the problem may be related to latest sdl2 versions on debian trixie or so. Also, do we have arm64 binaries? Yeah, the game runs fine under emulation, just curious.

**Comment by salvalie** [comment]
@stijn-volckaert @XenGi  seems solved with SDL_VIDEO_FULLSCREEN_DISPLAY=0 SDL_VIDEO_WINDOW_POS=0,0 SDL_VIDEO_CENTERED=1 SDL_VIDEODRIVER=wayland

**Comment by XenGi** [comment]
````
$ pacman -Q sdl2
sdl2-compat 2.32.54-1
$ pacman -Q sdl3
sdl3 3.2.10-1
$ pacman -Q sdl2_ttf
sdl2_ttf 2.24.0-1
$ env LC_ALL=C SDL_VIDEO_FULLSCREEN_DISPLAY=0 SDL_VIDEO_WINDOW_POS=0,0 SDL_VIDEO_CENTERED=1 SDL_VIDEODRIVER=wayland ut
WARNING: using preference directory: /home/xengi/.utpg/System/
WARNING: Using system ini file: /home/xengi/.utpg/System/UnrealTournament.ini
WARNING: Using user ini file: /home/xengi/.utpg/System/User.ini
Inconsistent SDL window flags


History: USDLViewport::ResizeViewport <- UOpenGLRenderDevice::SetRes <- UOpenGLRenderDevice::Init <- USDLViewport::TryRenderDevice <- USDLViewport::OpenWindow <- UGameEngine::Init <- InitEngine <- main

Exiting due to error
```

After the Arch Linux update to SDL3 UT doesn't run in full screen mode anymore on my two monitor setup.  I deleted the libs that come with the patch to use the native ones on my system. The only remaining file with SDL in it's name is `/opt/ut/System64/SDLDrv.so` and I guess that's still needed.

I'm maintaining the game in the AUR so you can have a look here How it is installed: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=unrealtournament

```
$ grep -i fullscreen ~/.utpg/System/UnrealTournament.ini
StartupFullscreen=True
FullscreenColorBits=32
FullscreenViewportY=1440
FullscreenViewportX=2560
```

The error only starts happening when I set `StartupFullscreen=True`.

**Comment by XenGi** [comment]
The issue seems to only exists on multi monitor setups. On my notebook with just one screen everything still works fine.

**Comment by hexengraf** [comment]
The patched `OpenGLDrv.so` posted in #1838 fixes this issue for me under X11, however wayland is still broken.

**Comment by zjDrummond** [comment]
I'm having the same issue on my Kubuntu 25.04 system. I'm using Wayland, and the game only launches fullscreen zoomed in on one quadrant of the image. I'm not sure if it's running exclusive fullscreen or a windowed fullscreen. I can get into a menu to see settings. I basically just have to kill the game to return to desktop. I'm using a single 1440p monitor BTW.
